on: push
name: Ansible Lint
jobs:
  linter:
    name: Lint Ansible Playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Linter
        uses: kapost/ansible-lint@v1
        env:
          COLLECTIONS: community.general ansible.posix ansible.network

